// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/moderacao" | "/anuncios" | "/anuncios/[slug]" | "/cadastro" | "/como-funciona" | "/dashboard" | "/dashboard/anuncios" | "/dashboard/anuncios/novo" | "/dashboard/empresa" | "/dashboard/favoritos" | "/dashboard/logistica" | "/dashboard/mensagens" | "/dashboard/notificacoes" | "/dashboard/pagamentos" | "/dashboard/propostas" | "/empresas" | "/entrar" | "/recuperar-senha" | "/redefinir-senha" | "/verificar-email"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/moderacao": {}
  "/anuncios": {}
  "/anuncios/[slug]": { "slug": string; }
  "/cadastro": {}
  "/como-funciona": {}
  "/dashboard": {}
  "/dashboard/anuncios": {}
  "/dashboard/anuncios/novo": {}
  "/dashboard/empresa": {}
  "/dashboard/favoritos": {}
  "/dashboard/logistica": {}
  "/dashboard/mensagens": {}
  "/dashboard/notificacoes": {}
  "/dashboard/pagamentos": {}
  "/dashboard/propostas": {}
  "/empresas": {}
  "/entrar": {}
  "/recuperar-senha": {}
  "/redefinir-senha": {}
  "/verificar-email": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
