// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/admin/moderacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/moderacao">> = Specific
  const handler = {} as typeof import("../../src/app/admin/moderacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/anuncios/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/anuncios/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/anuncios/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/anuncios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/anuncios">> = Specific
  const handler = {} as typeof import("../../src/app/anuncios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cadastro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cadastro">> = Specific
  const handler = {} as typeof import("../../src/app/cadastro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/como-funciona/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/como-funciona">> = Specific
  const handler = {} as typeof import("../../src/app/como-funciona/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/anuncios/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/anuncios/novo">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/anuncios/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/anuncios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/anuncios">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/anuncios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/empresa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/empresa">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/empresa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/favoritos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/favoritos">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/favoritos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/logistica/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/logistica">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/logistica/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/mensagens/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mensagens">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/mensagens/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/notificacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notificacoes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/notificacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/pagamentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pagamentos">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/pagamentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/propostas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/propostas">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/propostas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/empresas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empresas">> = Specific
  const handler = {} as typeof import("../../src/app/empresas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/entrar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entrar">> = Specific
  const handler = {} as typeof import("../../src/app/entrar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recuperar-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recuperar-senha">> = Specific
  const handler = {} as typeof import("../../src/app/recuperar-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/redefinir-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/redefinir-senha">> = Specific
  const handler = {} as typeof import("../../src/app/redefinir-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/verificar-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verificar-email">> = Specific
  const handler = {} as typeof import("../../src/app/verificar-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
