export const publicListingCardSelect = {
  id: true,
  type: true,
  title: true,
  slug: true,
  status: true,
  quantity: true,
  availableQuantity: true,
  unit: true,
  unitPrice: true,
  currency: true,
  frequency: true,
  riskClassification: true,
  originDetails: true,
  ownTransport: true,
  requiresDocuments: true,
  city: true,
  state: true,
  latitude: true,
  longitude: true,
  publishedAt: true,
  createdAt: true,
  company: {
    select: {
      id: true,
      slug: true,
      tradeName: true,
      legalName: true,
      verification: true,
    },
  },
  createdBy: { select: { id: true, name: true } },
  category: { select: { id: true, name: true, slug: true } },
  material: { select: { id: true, name: true, slug: true } },
  media: {
    where: { status: 'READY' as const },
    orderBy: { sortOrder: 'asc' as const },
    select: { id: true, altText: true, sortOrder: true },
  },
} as const;
